name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      env:
        SONAR_LOGIN:  ${{ secrets.sonar_login }}
        SONAR_ORGANIZATION:  ${{ secrets.sonar_organization }}
        SONAR_PROJECT_KEY:  ${{ secrets.sonar_project_key }}
      run: |
        dotnet sonarscanner begin /k:$SONAR_PROJECT_KEY /o:$SONAR_ORGANIZATION /d:sonar.login=$SONAR_LOGIN
        dotnet build --configuration Release --no-restore
        dotnet sonarscanner end /d:sonar.login=$SONAR_LOGIN
    - name: Test
      run: dotnet test --no-restore --verbosity normal
