name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install global tools
      run: |
        dotnet tool install --global dotnet-sonarscanner
        dotnet tool install --global coverlet.console
    - name: Install dependencies
      run: dotnet restore
    - name: Test
      run: |
        dotnet test src/Phnx.Tests/Phnx.Tests.csproj --no-restore /p:CollectCoverage=true /p:CoverletOutput="../../"
        dotnet test src/AspNetCore.Tests/Phnx.AspNetCore.Tests.csproj --no-restore /p:CollectCoverage=true /p:MergeWith="../../coverage.json" /p:CoverletOutputFormat=opencover
    - name: Scan Quality
      env:
        SONAR_LOGIN:  ${{ secrets.sonar_login }}
        SONAR_ORGANIZATION:  ${{ secrets.sonar_organization }}
        SONAR_PROJECT_KEY:  ${{ secrets.sonar_project_key }}
        GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
      run: |
        dotnet sonarscanner begin /k:$SONAR_PROJECT_KEY /o:$SONAR_ORGANIZATION /d:sonar.login=$SONAR_LOGIN /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="./coverlet.opencover.xml"
        dotnet build --configuration Release --no-restore
        dotnet sonarscanner end /d:sonar.login=$SONAR_LOGIN
